#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
server:
  port: 8761

spring:
  application:
    name: first-eureka-server
eureka:
  instance:
    hostname: slave1
  client:
    service-url:
      defaultZone: http://slave2:8762/eureka/