#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#server:
#  port: 8761
#
#spring:
#  application:
#    name: first-eureka-server
#  profiles:
#    - slave1
#eureka:
#  instance:
#    hostname: slave1
#  client:
#    service-url:
#      defaultZone: http://slave2:8762/eureka/
#
#---
#server:
#  port: 8762
#spring:
#  application:
#    name: first-eureka-server
#  profiles:
#    - slave2
#
#eureka:
#  instance:
#    hostname: slave2
#  client:
#    service-url:
#      defaultZone: http://slave1:8762/eureka/
