server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootmybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xyc.springbootmybatis.entity

# showSql
logging:
  level:
    com:
      example:
        mapper: debug

